### ISSUE TITLE
Automatic amplitude calibration to reach sensation threshold

### ISSUE THREAD

**Issue by mathiassand** [med-material/vrtactility#18]
Automatically increment the amplitude until the user feels the sensation threshold, then stop - afterward, allow for manual increase/decrease of amplitude. After this, we need to reach the discomfort threshold. by manually increasing the amplitude.

**Comment by MartinGarenfeld** [comment]
The automatic increment is basically for the convenience of the experimenter (he/she does not need to manually press the decrease/increase button manually all the time during the calibration). But it is a good idea to include as a functionality in the calibration scene. So practically, a button that increases the amplitude by X.X mA every X.X seconds should be included. The amplitude increment should be adjustable from a edit field and the same for the time increment. I would say that it not necessary to implement a automatic amplitude decrease button, as this be handled by the manual amplitude decrease button that is already implemented in the calibration scene. 

The discomfort threshold only needs to be determined if/when we want to modulate amplitude in the feedback. So we can wait with implementing this feature in the calibration scene until then. You can of course do it if you really feel like it. But it is less pressing, since we agreed to conduct pilot testing on frequency and spatially modulated feedback first.

**Comment by kuff** [comment]
I think this has been scoped out.
